version: '3.4'

x-globals: &globals
  NAME: value

x-flask: &flask
  NAMEFLASK: value

x-db: &db
  MYSQL_ROOT_PASSWORD: root_password
  MYSQL_DATABASE: corona
  MYSQL_USER: user
  MYSQL_PASSWORD: password

services:
  flask:
    build: ./src/flask_app
    hostname: 'flask'
    restart: always
    environment:
      <<: *globals
      <<: *flask
    ports:
      - 5000:5000
    volumes:
      - ./src/flask:/app/

  db:
    image: mysql:8.0.19
    hostname: 'db'
    restart: always
    environment:
      <<: *globals
      <<: *db
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./src/db:/docker-entrypoint-initdb.d

volumes:
  db_data:
